apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rc0
  labels:
    name: mongo-replica-rc
spec:
  replicas: 1
  selector:
    name: mongo-replica-node0
  template:
    metadata:
      labels:
        name: mongo-replica-node0
    spec:
      containers:
      - name: mongo-replica-node0
        image: hyge/mongo-cluster
        env:
          - name: mongo_node_name
            value: mongo-replica-node
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage0
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage0
        emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rc1
  labels:
    name: mongo-replica-rc
spec:
  replicas: 1
  selector:
    name: mongo-replica-node1
  template:
    metadata:
      labels:
        name: mongo-replica-node1
    spec:
      containers:
      - name: mongo-replica-node1
        image: hyge/mongo-cluster
        env:
          - name: mongo_node_name
            value: mongo-replica-node
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage1
        emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rc2
  labels:
    name: mongo-replica-rc
spec:
  replicas: 1
  selector:
    name: mongo-replica-node2
  template:
    metadata:
      labels:
        name: mongo-replica-node2
    spec:
      containers:
      - name: mongo-replica-node2
        image: hyge/mongo-cluster
        env:
          - name: mongo_node_name
            value: mongo-replica-node
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-replica-storage2
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage2
        persistentVolumeClaim:
          claimName: mongo-claim-0
